
import { Task, TaskStatus, LogEntry } from './types';

export const INITIAL_TASKS: Task[] = [
    { id: 1, category: 'Bank & Cash', description: 'Collect bank statements (2018–Present)', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 2, category: 'Bank & Cash', description: 'Tag cash withdrawals as Petty Cash / Partner Drawings', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 3, category: 'Bank & Cash', description: 'Reconcile deposits to sales invoices', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 4, category: 'Bank & Cash', description: 'Prepare yearly bank reconciliation sheets', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 5, category: 'Supplier', description: 'Create supplier list', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 6, category: 'Supplier', description: 'Request Ledger / SOA from suppliers', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 7, category: 'Supplier', description: 'Match invoices vs payments', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 8, category: 'Supplier', description: 'Identify outstanding balances', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 9, category: 'Supplier', description: 'Create Supplier Balance Summary', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 10, category: 'Customer', description: 'Prepare customer list', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 11, category: 'Customer', description: 'Send outstanding confirmation messages', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 12, category: 'Customer', description: 'Match receipts to invoices', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 13, category: 'Customer', description: 'Prepare Customer Receivable Summary', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 14, category: 'Inventory', description: 'Create Stock Item Master', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 15, category: 'Inventory', description: 'Conduct Physical Stock Count (Store + Workshop)', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 16, category: 'Inventory', description: 'Mark items: Service Use vs Sale', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 17, category: 'Inventory', description: 'Value stock using last purchase rate', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 18, category: 'Inventory', description: 'Calculate COGS using formula', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 19, category: 'Expense', description: 'Classify Rent, Utilities, Telephone', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 20, category: 'Expense', description: 'Classify Salary & WPS', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 21, category: 'Expense', description: 'Classify Diesel / Transport expense', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 22, category: 'Expense', description: 'Classify Tools & Workshop Consumables', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 23, category: 'Expense', description: 'Classify Admin & Office Expenses', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 24, category: 'Ledger Structure', description: 'Create Chart of Accounts', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 25, category: 'Ledger Structure', description: 'Map Suppliers to Sundry Creditors', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 26, category: 'Ledger Structure', description: 'Map Customers to Sundry Debtors', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 27, category: 'Ledger Structure', description: 'Create Stock Groups by Category', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 28, category: 'Year-End', description: 'Confirm final closing stock value', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 29, category: 'Year-End', description: 'Post depreciation on tools & equipment', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 30, category: 'Year-End', description: 'Adjust accruals and prepayments', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 31, category: 'Year-End', description: 'Close Profit & Loss to Capital', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 32, category: 'Year-End', description: 'Carry balances to next year', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 33, category: 'Final Reports', description: 'Prepare Trial Balance (Final)', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 34, category: 'Final Reports', description: 'Prepare Profit & Loss Statement', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 35, category: 'Final Reports', description: 'Prepare Balance Sheet', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 36, category: 'Final Reports', description: 'Prepare Inventory Valuation Report', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 37, category: 'Software Implementation', description: 'Select Accounting Software', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 38, category: 'Software Implementation', description: 'Enter Opening Balances', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 39, category: 'Software Implementation', description: 'Import Suppliers & Customers', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 40, category: 'Software Implementation', description: 'Import Inventory Master', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 41, category: 'Software Implementation', description: 'Configure Invoice Template', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 42, category: 'Software Implementation', description: 'Test Sample Entries', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 43, category: 'Training', description: 'Train accountant on daily entry', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 44, category: 'Training', description: 'Train on bank reconciliation follow-ups', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 45, category: 'Training', description: 'Train on monthly closing cycle', deadline: '', responsible: '', status: TaskStatus.Pending },
    { id: 46, category: 'Training', description: 'Provide SOP documentation', deadline: '', responsible: '', status: TaskStatus.Pending },
];

export const INITIAL_LOGS: LogEntry[] = [
    { id: 1, date: new Date().toISOString().split('T')[0], workedOn: 'Initial setup', hours: '1', blockers: 'None', nextActions: 'Begin bank reconciliation' }
];
